
include ../DEFAULTS.inc

IFLAGS = -I../equil -I../harvest -I../pentrc -I../vacuum -I$(MATHINC) -I$(NETCDFINC)
F90 = $(FC) $(FFLAGS) $(OMPFLAG) $(IFLAGS) $(RECURSFLAG) $(LEGACYFLAG)
export FFLAGS # for sub-makes

.f.o:
	$(F90) -c $*.f

.F.o:
	$(F90) -c $*.F

LIBDIR = ../lib

LIBS = \
	-lpentrc \
	-llsode \
	-lequil \
	-lvac \
	-lharvest \

OBJS = \
	debug.o \
	dcon_mod.o \
	mercier.o \
	bal.o \
	fourfit.o \
	sing.o \
	ode_output.o \
	free.o \
	ode.o \
	dcon_netcdf.o \
	resist.o \
	dcon.o

# targets

all: harvest lsode equil vacuum pentrc dcon

harvest:
	cd ../; git submodule init; git submodule update
	cd ../harvest; make FC=$(FC) CC=$(CC) GACODE_ROOT= -f Makefile libharvest.a
	mkdir -p ../lib
	cp -f ../harvest/libharvest.a ../lib/

lsode:
	cd ../lsode; make

equil:
	cd ../equil; make

vacuum:
	cd ../vacuum; make

pentrc:
	cd ../pentrc; make pentrc

# note we explicitly make pentrc to force sync the compile-time version variable
dcon: pentrc vacuum equil lsode harvest $(OBJS)
	$(F90) -o dcon $(OBJS) -L$(LIBDIR) $(LIBS) -L$(MATHDIR) $(MATHLIBS) -L$(NETCDFDIR) $(NETCDFLIBS) $(NETCDF_EXTRA_LIBS) $(LDFLAGS)
	mkdir -p ../bin
	cp -f dcon ../bin

clean:
	rm -f *.o *.mod *.out *.bin sum.dat *~ *.diff dcon *.original

# dependencies

dcon_mod.o: equil pentrc
mercier.o: dcon_mod.o
bal.o: dcon_mod.o
fourfit.o: equil pentrc dcon_mod.o
sing.o: fourfit.o
debug.o: equil
ode_output.o: dcon_mod.o sing.o debug.o
ode.o: ode_output.o free.o
dcon_netcdf.o: dcon_mod.o sing.o
free.o: equil dcon_netcdf.o ode_output.o
resist.o: dcon_mod.o
dcon.o: equil pentrc dcon_mod.o sing.o debug.o ode_output.o dcon_netcdf.o bal.o mercier.o ode.o free.o resist.o
